# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-09 12:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dates',
            name='curr_week',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
