# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dates_curr_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='total_lectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fe1', models.IntegerField(default=0)),
                ('physics', models.IntegerField(default=0)),
                ('chemistry', models.IntegerField(default=0)),
                ('maths', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='be2',
            name='student',
        ),
        migrations.RemoveField(
            model_name='se2',
            name='student',
        ),
        migrations.RemoveField(
            model_name='te2',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='avg_attendance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='sub1_attendance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='sub1_present',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='sub2_attendance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='sub2_present',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='sub3_attendance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='sub3_present',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='total_present',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='division',
            field=models.CharField(choices=[('FE1', 'FE1'), ('SE1', 'SE1'), ('BE1', 'BE1'), ('TE1', 'TE1')], max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('chemistry', 'Chemistry'), ('coa', 'C.O.A'), ('deld', 'D.E.L.D'), ('maths', 'Maths'), ('mp', 'M.P'), ('os', 'O.S'), ('physics', 'Physics'), ('sdl', 'S.D.L'), ('sub1', 'Sub1'), ('sub2', 'Sub2'), ('sub3', 'Sub3'), ('toc', 'T.O.C')], max_length=50),
        ),
        migrations.DeleteModel(
            name='BE2',
        ),
        migrations.DeleteModel(
            name='SE2',
        ),
        migrations.DeleteModel(
            name='TE2',
        ),
    ]
