# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180914_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='development_fee',
            field=models.FloatField(default=8414),
        ),
        migrations.AddField(
            model_name='student',
            name='tution_fee',
            field=models.FloatField(default=84136),
        ),
        migrations.AddField(
            model_name='student',
            name='university_fee',
            field=models.FloatField(default=2000),
        ),
    ]
