# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180915_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='exam_fee',
            field=models.FloatField(default=0),
        ),
    ]
