# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-16 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_student_exam_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent_id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'male'), ('other', 'other'), ('female', 'female')], max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('relation', models.CharField(choices=[('father', 'father'), ('guardian', 'guardian'), ('mother', 'mother')], max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
    ]
