# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-17 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180917_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='be1',
            options={'verbose_name_plural': 'BE1'},
        ),
        migrations.AlterModelOptions(
            name='total_lectures',
            options={'verbose_name_plural': 'total lectures'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='attendance',
        ),
        migrations.AddField(
            model_name='be1',
            name='weekly_attendance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fe1',
            name='weekly_attendance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='se1',
            name='weekly_attendance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='te1',
            name='weekly_attendance',
            field=models.FloatField(default=0),
        ),
    ]
