# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-18 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180917_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='be1',
            name='ics_f',
        ),
        migrations.RemoveField(
            model_name='se1',
            name='deld_f',
        ),
        migrations.RemoveField(
            model_name='te1',
            name='os_f',
        ),
    ]
